@extends('layouts.app')
@section('title','Biz haqimizda')
@section('content')
<div class="container " style="margin-top:100px ">
     <h2 class="py-3">Mang`itobod Qishlog'ining  Tarixi</h2>
     <p  class="h-25 py-3"> Mang‘itobod tuman Urgut tumani shimoliy qismida joylashgan bo‘lib, atrofi Birlik, Sovg‘on, Oqmachit, Bekravot qishloqlari bilan chegaradosh. Ota-onalarimizning yozib qoldirishlaricha qishloqning paydo bo‘lganligi qariyb 300 yillik tarixga ega.
      Dastlab axolimiz Mang‘it elining ming sulolasidan kelgan to‘rt oiladan tarkalgan. Shundan boshlab asta-sekinlik bilan ko‘chib kelgan Xalq utroqlashib qishloq shakliga kelgan. Dehqonchilik va chorvachilik yaxshi rivojlangan, shundan sung Mangitobod axolisi kupayib xozirda katta maxallaga aylandi. Mangitobod maxallasida dastavval birgina masjid bulgan usha masjidda namoz ukib xovlisida kunduz paytlari oksokollar yigilishib Mangitobod qishlogini qaysi yo‘l bilan bo‘lmasin qishloq xo‘jalik soxasini rivojlantirish yo‘llarini maslaxatlashib chora tadbirlarini izlashgan. O‘sha davrda Mangitobod qishlog‘iga oqarsuv muammosi eng og‘ir muammo bo‘lgan, o‘sha muammoni xal etish uchun qishloq axolisi qozon ariq nomi bilan ataladigan arig‘ini qazib suvni keltirishgan.
      Shu tariqa Mangitobod qishlog‘i qishloq xo‘jalik soxasida rivojlanib bir qancha yutuqlarga erishgan. Ushbu jarayonda muntazam katnashgan Shukurov Rashid, Xakimov Xofiz, Oblokulov Melikullar uz xissalarini kushib faol xizmat kursatgan.
      Sobik SSSR shuro xukumati davrida tasodif boshlangan ulug Vatan urushi davrida Mangitobod kishlogidan bir nechta fukarolar sovuk front katnashchilari buldilar jumladan: Eshonkulov Sulton, kizil yulduz ordeni soxibi Pulat Esonov, Rajabboy Begimkulov, Abdullo Jurayev, Shernazarov Xolmuratov, Egamurod Mirzayev, Mamatkul Pardayev, Fozil Ibragimov, Jamol Suyunovlar 1941-1945 yillardagi ulug Vatan urushida faol katnashib xalkimiz Vatanimiz tinchligi uchun xizmat kilganlar.
      Sobik shuro xukumati davrida ( kolxoz davrida) Mangitobod kishlogidan bir nechta malakali mutaxasislar yetishib chikkkan. Jumladan, Pulat Esanov, Saidmurod Kurbonov, Musurmon Radjabov, Eshim Xolmurzayev, Obloyar Shadiyarovlar uzlarining munosib xissalarni Vatan ravnaki uchun kushganlar.
      Uzbekiston Respublikasi Mustakllikka erishgandan sung uzini uzi boshkarish organlari faoliyatini takolmillashtirish Uzbekiston Respublikasi Prezidentining farmoniga asosan Respublikada maxalla tashkiloti tashkil etildi Jumladan: Mangitobod maxallasi 1992-yil oktyabr oyida tashkil topgan bo‘lib, maxalladaboshlab 2860 nafar axoli mavjud bulgan. Xozirga vaktga kelib Maxallada jami axoli 6390 nafar bulib, shundan erkaklar 3297 ta, ayollar soni 3093 nafar. Shundan 18-30 yosh 1746 nafar, 31-55 yoshgacha 1777 nafar, va 55 yoshdan yukori bulgan fukarolar soni 460 nafar, bogcha yoshidagilar esa 581-nafarni tashkil etadi.
      Shuningdek Mangitobod maxallasida ayni vaktda bitta o‘rta maktab, unda 1126 nafar o‘quvchi 86 nafar o‘qituvchi faoliyat ko‘rsatmoqda,1 ta KVP, 1 ta Maishix xizmat va servis Kasb xunar kolleji faoliyat ko‘rsatmoqda. Ushbu tashkilotlarda jami 266 nafar mutaxxasislar mexnat kilib kelmokda.
      Mangitobod maxallasida qadimdan tarixiy yodgorlik bo‘lib kelgan 11 tatepalik mavjud bo‘lib bular davlat muxofazasida saklanib kelmokda. Mangitobod maxallasida 19 ta savdo dukoni mavjud bulib shundan 16 tasioziq-ovqat do‘konlari va 3 ta xujalik mollari dukoni faoliyat olib bormoqda.
      Bundan tashqari maishiy xizmat uyi ustaxona, apteka, dizayner xonasi va kompyuter xonasi ishlab turibdi. 3 ta qassobxona xam xalqimizning go‘sht mahsulotlariga bo‘lgan talabini qondirib kelmoqda. Maxallada xozirgi kunda 6390 ta aholi yashab kelmoqda. Xotinqizlar 3093 ta. Nuroniylar-pensianerlar 376 tani tashkel etadi. Yoshlar shug‘ullanishi uchun 2 ta stadion 1 ta mini stadion xizmat ko‘rsatmoqda. Hozirgi kunda maxallada
      5 nafar xoji ota va xoji onalar yashaydi. Axoli asosan bog‘dorchilik va uzumchilik faoliyati bilan shug‘ullanib uzum–mayiz ëtishtirib kelmoqda. 46 ta fermer xo‘jaligida xalqimiz o‘ziga berilgan reja va topshiriqlarni munosib uddalab kelmoqda. Davlatimiz, yurtboshimiz tomanidan qabul qilingan qaror va farmonlarni xalqimiz ongli ravishda tushunib va amal qilib zamon bilan hamnafas yashab kelmoqda. Biz mustaqil yurt ravnaqiga munosib hissa qo‘shish uchun astoydil kurashib yashaymiz.
      Ayni paytda Mangitobod maxallasida 100 nafardan ziyod oliy malumotli mutaxassislar va 1 nafar fan nomzodi davlatimiz ravnaqiga o‘z xissasini ko‘shib kelmokda.
     </p>
    </div>
@endsection
